/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.1-50-ga4e1dd6940-20220323"
#endif /* AVUTIL_FFVERSION_H */
